%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.0

-ifndef(cmd).
-define(cmd, true).

-define(cmd_gpb_version, "4.10.0").

-ifndef('CMDPING1_PB_H').
-define('CMDPING1_PB_H', true).
-record('CmdPing1',
        {'Ii' = 0               :: integer() | undefined, % = 1, 32 bits
         'Ss' = []              :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('CMDPING2_PB_H').
-define('CMDPING2_PB_H', true).
-record('CmdPing2',
        {'Ii' = 0               :: integer() | undefined, % = 1, 32 bits
         'Ss' = []              :: iodata() | undefined % = 2
        }).
-endif.

-endif.
