%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.0

-ifndef(msg).
-define(msg, true).

-define(msg_gpb_version, "4.10.0").

-ifndef('MSGPONG1_PB_H').
-define('MSGPONG1_PB_H', true).
-record('MsgPong1',
        {'Ii' = 0               :: integer() | undefined, % = 1, 32 bits
         'Ss' = []              :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('MSGPONG2_PB_H').
-define('MSGPONG2_PB_H', true).
-record('MsgPong2',
        {'Ii' = 0               :: integer() | undefined, % = 1, 32 bits
         'Ss' = []              :: iodata() | undefined % = 2
        }).
-endif.

-endif.
