%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.0

-ifndef(person).
-define(person, true).

-define(person_gpb_version, "4.10.0").

-ifndef('PERSON_PB_H').
-define('PERSON_PB_H', true).
-record('Person',
        {name = []              :: iodata() | undefined, % = 1
         id = 0                 :: integer() | undefined, % = 2, 32 bits
         email = []             :: iodata() | undefined % = 3
        }).
-endif.

-endif.
