%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.0

-ifndef(type).
-define(type, true).

-define(type_gpb_version, "4.10.0").

-ifndef('PROTODATA_PB_H').
-define('PROTODATA_PB_H', true).
-record('ProtoData',
        {'Head' = 'ID_UNKNOW'   :: 'ID_UNKNOW' | 'ID_CmdPing1' | 'ID_CmdPing2' | integer() | undefined, % = 1, enum ProtoID
         'Body' = <<>>          :: iodata() | undefined % = 2
        }).
-endif.

-endif.
