%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.0
-module(all_pb).

-export([encode_msg/1, encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3, merge_msgs/4]).
-export([verify_msg/1, verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export(['enum_symbol_by_value_cmdTest1.info'/1, 'enum_value_by_symbol_cmdTest1.info'/1]).
-export(['enum_symbol_by_value_cmdTest2.info'/1, 'enum_value_by_symbol_cmdTest2.info'/1]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).

-include("all_pb.hrl").
-include("gpb.hrl").

%% enumerated types
-type 'cmdTest1.info'() :: unknown | proto_id | aaa | bbb.
-type 'cmdTest2.info'() :: unknown | proto_id | bag | email.
-export_type(['cmdTest1.info'/0, 'cmdTest2.info'/0]).

%% message types
-type protoID() :: #protoID{}.

-type cmdTest1() :: #cmdTest1{}.

-type cmdTest2() :: #cmdTest2{}.

-type msgTest1() :: #msgTest1{}.

-type msgTest2() :: #msgTest2{}.

-export_type(['protoID'/0, 'cmdTest1'/0, 'cmdTest2'/0, 'msgTest1'/0, 'msgTest2'/0]).

-spec encode_msg(#protoID{} | #cmdTest1{} | #cmdTest2{} | #msgTest1{} | #msgTest2{}) -> binary().
encode_msg(Msg) when tuple_size(Msg) >= 1 ->
    encode_msg(Msg, element(1, Msg), []).

-spec encode_msg(#protoID{} | #cmdTest1{} | #cmdTest2{} | #msgTest1{} | #msgTest2{}, atom() | list()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) ->
    encode_msg(Msg, MsgName, []);
encode_msg(Msg, Opts)
    when tuple_size(Msg) >= 1, is_list(Opts) ->
    encode_msg(Msg, element(1, Msg), Opts).

-spec encode_msg(#protoID{} | #cmdTest1{} | #cmdTest2{} | #msgTest1{} | #msgTest2{}, atom(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
      true -> verify_msg(Msg, MsgName, Opts);
      false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      protoID ->
	  encode_msg_protoID(id(Msg, TrUserData), TrUserData);
      cmdTest1 ->
	  encode_msg_cmdTest1(id(Msg, TrUserData), TrUserData);
      cmdTest2 ->
	  encode_msg_cmdTest2(id(Msg, TrUserData), TrUserData);
      msgTest1 ->
	  encode_msg_msgTest1(id(Msg, TrUserData), TrUserData);
      msgTest2 ->
	  encode_msg_msgTest2(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_protoID(Msg, TrUserData) ->
    encode_msg_protoID(Msg, <<>>, TrUserData).


encode_msg_protoID(#protoID{proto_id = F1, data = F2},
		   Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
	    true ->
		begin
		  TrF1 = id(F1, TrUserData),
		  if TrF1 =:= 0 -> Bin;
		     true ->
			 e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData)
		  end
		end
	 end,
    if F2 == undefined -> B1;
       true ->
	   begin
	     TrF2 = id(F2, TrUserData),
	     case iolist_size(TrF2) of
	       0 -> B1;
	       _ -> e_type_bytes(TrF2, <<B1/binary, 18>>, TrUserData)
	     end
	   end
    end.

encode_msg_cmdTest1(Msg, TrUserData) ->
    encode_msg_cmdTest1(Msg, <<>>, TrUserData).


encode_msg_cmdTest1(#cmdTest1{ii = F1, ss = F2}, Bin,
		    TrUserData) ->
    B1 = if F1 == undefined -> Bin;
	    true ->
		begin
		  TrF1 = id(F1, TrUserData),
		  if TrF1 =:= 0 -> Bin;
		     true ->
			 e_type_int32(TrF1, <<Bin/binary, 16>>, TrUserData)
		  end
		end
	 end,
    if F2 == undefined -> B1;
       true ->
	   begin
	     TrF2 = id(F2, TrUserData),
	     case is_empty_string(TrF2) of
	       true -> B1;
	       false ->
		   e_type_string(TrF2, <<B1/binary, 26>>, TrUserData)
	     end
	   end
    end.

encode_msg_cmdTest2(Msg, TrUserData) ->
    encode_msg_cmdTest2(Msg, <<>>, TrUserData).


encode_msg_cmdTest2(#cmdTest2{ii = F1, ss = F2}, Bin,
		    TrUserData) ->
    B1 = if F1 == undefined -> Bin;
	    true ->
		begin
		  TrF1 = id(F1, TrUserData),
		  if TrF1 =:= 0 -> Bin;
		     true ->
			 e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData)
		  end
		end
	 end,
    if F2 == undefined -> B1;
       true ->
	   begin
	     TrF2 = id(F2, TrUserData),
	     case is_empty_string(TrF2) of
	       true -> B1;
	       false ->
		   e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
	     end
	   end
    end.

encode_msg_msgTest1(Msg, TrUserData) ->
    encode_msg_msgTest1(Msg, <<>>, TrUserData).


encode_msg_msgTest1(#msgTest1{ii = F1, ss = F2}, Bin,
		    TrUserData) ->
    B1 = if F1 == undefined -> Bin;
	    true ->
		begin
		  TrF1 = id(F1, TrUserData),
		  if TrF1 =:= 0 -> Bin;
		     true ->
			 e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData)
		  end
		end
	 end,
    if F2 == undefined -> B1;
       true ->
	   begin
	     TrF2 = id(F2, TrUserData),
	     case is_empty_string(TrF2) of
	       true -> B1;
	       false ->
		   e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
	     end
	   end
    end.

encode_msg_msgTest2(Msg, TrUserData) ->
    encode_msg_msgTest2(Msg, <<>>, TrUserData).


encode_msg_msgTest2(#msgTest2{ii = F1, ss = F2}, Bin,
		    TrUserData) ->
    B1 = if F1 == undefined -> Bin;
	    true ->
		begin
		  TrF1 = id(F1, TrUserData),
		  if TrF1 =:= 0 -> Bin;
		     true ->
			 e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData)
		  end
		end
	 end,
    if F2 == undefined -> B1;
       true ->
	   begin
	     TrF2 = id(F2, TrUserData),
	     case is_empty_string(TrF2) of
	       true -> B1;
	       false ->
		   e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
	     end
	   end
    end.

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 ->
    e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) ->
    e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData)
    when 0 =< Value, Value =< 127 ->
    <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData)
    when 0 =< Value, Value =< 127 ->
    <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) ->
    <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) ->
    <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData)
    when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData)
    when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) ->
    <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) ->
    <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) ->
    <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) ->
    <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) ->
    <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) ->
    <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) ->
    <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) ->
    <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) ->
    <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) ->
    <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) ->
    <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) ->
    <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) ->
    not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
      true -> true;
      false -> string_has_chars(T)
    end;
string_has_chars(B)
    when is_binary(B), byte_size(B) =/= 0 ->
    true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) -> false;
string_has_chars([]) -> false.


decode_msg(Bin, MsgName) when is_binary(Bin) ->
    decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason ->
        StackTrace = erlang:get_stacktrace(),
        error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit(protoID, Bin, TrUserData) ->
    id(decode_msg_protoID(Bin, TrUserData), TrUserData);
decode_msg_2_doit(cmdTest1, Bin, TrUserData) ->
    id(decode_msg_cmdTest1(Bin, TrUserData), TrUserData);
decode_msg_2_doit(cmdTest2, Bin, TrUserData) ->
    id(decode_msg_cmdTest2(Bin, TrUserData), TrUserData);
decode_msg_2_doit(msgTest1, Bin, TrUserData) ->
    id(decode_msg_msgTest1(Bin, TrUserData), TrUserData);
decode_msg_2_doit(msgTest2, Bin, TrUserData) ->
    id(decode_msg_msgTest2(Bin, TrUserData), TrUserData).



decode_msg_protoID(Bin, TrUserData) ->
    dfp_read_field_def_protoID(Bin, 0, 0, id(0, TrUserData),
			       id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_protoID(<<8, Rest/binary>>, Z1, Z2,
			   F@_1, F@_2, TrUserData) ->
    d_field_protoID_proto_id(Rest, Z1, Z2, F@_1, F@_2,
			     TrUserData);
dfp_read_field_def_protoID(<<18, Rest/binary>>, Z1, Z2,
			   F@_1, F@_2, TrUserData) ->
    d_field_protoID_data(Rest, Z1, Z2, F@_1, F@_2,
			 TrUserData);
dfp_read_field_def_protoID(<<>>, 0, 0, F@_1, F@_2, _) ->
    #protoID{proto_id = F@_1, data = F@_2};
dfp_read_field_def_protoID(Other, Z1, Z2, F@_1, F@_2,
			   TrUserData) ->
    dg_read_field_def_protoID(Other, Z1, Z2, F@_1, F@_2,
			      TrUserData).

dg_read_field_def_protoID(<<1:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, F@_2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_protoID(Rest, N + 7, X bsl N + Acc,
			      F@_1, F@_2, TrUserData);
dg_read_field_def_protoID(<<0:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_protoID_proto_id(Rest, 0, 0, F@_1, F@_2,
				   TrUserData);
      18 ->
	  d_field_protoID_data(Rest, 0, 0, F@_1, F@_2,
			       TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_protoID(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    1 ->
		skip_64_protoID(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    2 ->
		skip_length_delimited_protoID(Rest, 0, 0, F@_1, F@_2,
					      TrUserData);
	    3 ->
		skip_group_protoID(Rest, Key bsr 3, 0, F@_1, F@_2,
				   TrUserData);
	    5 -> skip_32_protoID(Rest, 0, 0, F@_1, F@_2, TrUserData)
	  end
    end;
dg_read_field_def_protoID(<<>>, 0, 0, F@_1, F@_2, _) ->
    #protoID{proto_id = F@_1, data = F@_2}.

d_field_protoID_proto_id(<<1:1, X:7, Rest/binary>>, N,
			 Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_protoID_proto_id(Rest, N + 7, X bsl N + Acc,
			     F@_1, F@_2, TrUserData);
d_field_protoID_proto_id(<<0:1, X:7, Rest/binary>>, N,
			 Acc, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    id(Res, TrUserData)
			  end,
			  Rest},
    dfp_read_field_def_protoID(RestF, 0, 0, NewFValue, F@_2,
			       TrUserData).

d_field_protoID_data(<<1:1, X:7, Rest/binary>>, N, Acc,
		     F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_protoID_data(Rest, N + 7, X bsl N + Acc, F@_1,
			 F@_2, TrUserData);
d_field_protoID_data(<<0:1, X:7, Rest/binary>>, N, Acc,
		     F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {id(binary:copy(Bytes), TrUserData), Rest2}
			 end,
    dfp_read_field_def_protoID(RestF, 0, 0, F@_1, NewFValue,
			       TrUserData).

skip_varint_protoID(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		    F@_1, F@_2, TrUserData) ->
    skip_varint_protoID(Rest, Z1, Z2, F@_1, F@_2,
			TrUserData);
skip_varint_protoID(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		    F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_protoID(Rest, Z1, Z2, F@_1, F@_2,
			       TrUserData).

skip_length_delimited_protoID(<<1:1, X:7, Rest/binary>>,
			      N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    skip_length_delimited_protoID(Rest, N + 7,
				  X bsl N + Acc, F@_1, F@_2, TrUserData);
skip_length_delimited_protoID(<<0:1, X:7, Rest/binary>>,
			      N, Acc, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_protoID(Rest2, 0, 0, F@_1, F@_2,
			       TrUserData).

skip_group_protoID(Bin, FNum, Z2, F@_1, F@_2,
		   TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_protoID(Rest, 0, Z2, F@_1, F@_2,
			       TrUserData).

skip_32_protoID(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		F@_2, TrUserData) ->
    dfp_read_field_def_protoID(Rest, Z1, Z2, F@_1, F@_2,
			       TrUserData).

skip_64_protoID(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		F@_2, TrUserData) ->
    dfp_read_field_def_protoID(Rest, Z1, Z2, F@_1, F@_2,
			       TrUserData).

decode_msg_cmdTest1(Bin, TrUserData) ->
    dfp_read_field_def_cmdTest1(Bin, 0, 0,
				id(0, TrUserData), id(<<>>, TrUserData),
				TrUserData).

dfp_read_field_def_cmdTest1(<<16, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_cmdTest1_ii(Rest, Z1, Z2, F@_1, F@_2,
			TrUserData);
dfp_read_field_def_cmdTest1(<<26, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_cmdTest1_ss(Rest, Z1, Z2, F@_1, F@_2,
			TrUserData);
dfp_read_field_def_cmdTest1(<<>>, 0, 0, F@_1, F@_2,
			    _) ->
    #cmdTest1{ii = F@_1, ss = F@_2};
dfp_read_field_def_cmdTest1(Other, Z1, Z2, F@_1, F@_2,
			    TrUserData) ->
    dg_read_field_def_cmdTest1(Other, Z1, Z2, F@_1, F@_2,
			       TrUserData).

dg_read_field_def_cmdTest1(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_cmdTest1(Rest, N + 7, X bsl N + Acc,
			       F@_1, F@_2, TrUserData);
dg_read_field_def_cmdTest1(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      16 ->
	  d_field_cmdTest1_ii(Rest, 0, 0, F@_1, F@_2, TrUserData);
      26 ->
	  d_field_cmdTest1_ss(Rest, 0, 0, F@_1, F@_2, TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_cmdTest1(Rest, 0, 0, F@_1, F@_2,
				     TrUserData);
	    1 ->
		skip_64_cmdTest1(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    2 ->
		skip_length_delimited_cmdTest1(Rest, 0, 0, F@_1, F@_2,
					       TrUserData);
	    3 ->
		skip_group_cmdTest1(Rest, Key bsr 3, 0, F@_1, F@_2,
				    TrUserData);
	    5 ->
		skip_32_cmdTest1(Rest, 0, 0, F@_1, F@_2, TrUserData)
	  end
    end;
dg_read_field_def_cmdTest1(<<>>, 0, 0, F@_1, F@_2, _) ->
    #cmdTest1{ii = F@_1, ss = F@_2}.

d_field_cmdTest1_ii(<<1:1, X:7, Rest/binary>>, N, Acc,
		    F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_cmdTest1_ii(Rest, N + 7, X bsl N + Acc, F@_1,
			F@_2, TrUserData);
d_field_cmdTest1_ii(<<0:1, X:7, Rest/binary>>, N, Acc,
		    _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    id(Res, TrUserData)
			  end,
			  Rest},
    dfp_read_field_def_cmdTest1(RestF, 0, 0, NewFValue,
				F@_2, TrUserData).

d_field_cmdTest1_ss(<<1:1, X:7, Rest/binary>>, N, Acc,
		    F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_cmdTest1_ss(Rest, N + 7, X bsl N + Acc, F@_1,
			F@_2, TrUserData);
d_field_cmdTest1_ss(<<0:1, X:7, Rest/binary>>, N, Acc,
		    F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {id(binary:copy(Bytes), TrUserData), Rest2}
			 end,
    dfp_read_field_def_cmdTest1(RestF, 0, 0, F@_1,
				NewFValue, TrUserData).

skip_varint_cmdTest1(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    skip_varint_cmdTest1(Rest, Z1, Z2, F@_1, F@_2,
			 TrUserData);
skip_varint_cmdTest1(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_cmdTest1(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_length_delimited_cmdTest1(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    skip_length_delimited_cmdTest1(Rest, N + 7,
				   X bsl N + Acc, F@_1, F@_2, TrUserData);
skip_length_delimited_cmdTest1(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_cmdTest1(Rest2, 0, 0, F@_1, F@_2,
				TrUserData).

skip_group_cmdTest1(Bin, FNum, Z2, F@_1, F@_2,
		    TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_cmdTest1(Rest, 0, Z2, F@_1, F@_2,
				TrUserData).

skip_32_cmdTest1(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_cmdTest1(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_64_cmdTest1(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_cmdTest1(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

decode_msg_cmdTest2(Bin, TrUserData) ->
    dfp_read_field_def_cmdTest2(Bin, 0, 0,
				id(0, TrUserData), id(<<>>, TrUserData),
				TrUserData).

dfp_read_field_def_cmdTest2(<<8, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_cmdTest2_ii(Rest, Z1, Z2, F@_1, F@_2,
			TrUserData);
dfp_read_field_def_cmdTest2(<<18, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_cmdTest2_ss(Rest, Z1, Z2, F@_1, F@_2,
			TrUserData);
dfp_read_field_def_cmdTest2(<<>>, 0, 0, F@_1, F@_2,
			    _) ->
    #cmdTest2{ii = F@_1, ss = F@_2};
dfp_read_field_def_cmdTest2(Other, Z1, Z2, F@_1, F@_2,
			    TrUserData) ->
    dg_read_field_def_cmdTest2(Other, Z1, Z2, F@_1, F@_2,
			       TrUserData).

dg_read_field_def_cmdTest2(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_cmdTest2(Rest, N + 7, X bsl N + Acc,
			       F@_1, F@_2, TrUserData);
dg_read_field_def_cmdTest2(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_cmdTest2_ii(Rest, 0, 0, F@_1, F@_2, TrUserData);
      18 ->
	  d_field_cmdTest2_ss(Rest, 0, 0, F@_1, F@_2, TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_cmdTest2(Rest, 0, 0, F@_1, F@_2,
				     TrUserData);
	    1 ->
		skip_64_cmdTest2(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    2 ->
		skip_length_delimited_cmdTest2(Rest, 0, 0, F@_1, F@_2,
					       TrUserData);
	    3 ->
		skip_group_cmdTest2(Rest, Key bsr 3, 0, F@_1, F@_2,
				    TrUserData);
	    5 ->
		skip_32_cmdTest2(Rest, 0, 0, F@_1, F@_2, TrUserData)
	  end
    end;
dg_read_field_def_cmdTest2(<<>>, 0, 0, F@_1, F@_2, _) ->
    #cmdTest2{ii = F@_1, ss = F@_2}.

d_field_cmdTest2_ii(<<1:1, X:7, Rest/binary>>, N, Acc,
		    F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_cmdTest2_ii(Rest, N + 7, X bsl N + Acc, F@_1,
			F@_2, TrUserData);
d_field_cmdTest2_ii(<<0:1, X:7, Rest/binary>>, N, Acc,
		    _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    id(Res, TrUserData)
			  end,
			  Rest},
    dfp_read_field_def_cmdTest2(RestF, 0, 0, NewFValue,
				F@_2, TrUserData).

d_field_cmdTest2_ss(<<1:1, X:7, Rest/binary>>, N, Acc,
		    F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_cmdTest2_ss(Rest, N + 7, X bsl N + Acc, F@_1,
			F@_2, TrUserData);
d_field_cmdTest2_ss(<<0:1, X:7, Rest/binary>>, N, Acc,
		    F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {id(binary:copy(Bytes), TrUserData), Rest2}
			 end,
    dfp_read_field_def_cmdTest2(RestF, 0, 0, F@_1,
				NewFValue, TrUserData).

skip_varint_cmdTest2(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    skip_varint_cmdTest2(Rest, Z1, Z2, F@_1, F@_2,
			 TrUserData);
skip_varint_cmdTest2(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_cmdTest2(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_length_delimited_cmdTest2(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    skip_length_delimited_cmdTest2(Rest, N + 7,
				   X bsl N + Acc, F@_1, F@_2, TrUserData);
skip_length_delimited_cmdTest2(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_cmdTest2(Rest2, 0, 0, F@_1, F@_2,
				TrUserData).

skip_group_cmdTest2(Bin, FNum, Z2, F@_1, F@_2,
		    TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_cmdTest2(Rest, 0, Z2, F@_1, F@_2,
				TrUserData).

skip_32_cmdTest2(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_cmdTest2(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_64_cmdTest2(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_cmdTest2(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

decode_msg_msgTest1(Bin, TrUserData) ->
    dfp_read_field_def_msgTest1(Bin, 0, 0,
				id(0, TrUserData), id(<<>>, TrUserData),
				TrUserData).

dfp_read_field_def_msgTest1(<<8, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_msgTest1_ii(Rest, Z1, Z2, F@_1, F@_2,
			TrUserData);
dfp_read_field_def_msgTest1(<<18, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_msgTest1_ss(Rest, Z1, Z2, F@_1, F@_2,
			TrUserData);
dfp_read_field_def_msgTest1(<<>>, 0, 0, F@_1, F@_2,
			    _) ->
    #msgTest1{ii = F@_1, ss = F@_2};
dfp_read_field_def_msgTest1(Other, Z1, Z2, F@_1, F@_2,
			    TrUserData) ->
    dg_read_field_def_msgTest1(Other, Z1, Z2, F@_1, F@_2,
			       TrUserData).

dg_read_field_def_msgTest1(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_msgTest1(Rest, N + 7, X bsl N + Acc,
			       F@_1, F@_2, TrUserData);
dg_read_field_def_msgTest1(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_msgTest1_ii(Rest, 0, 0, F@_1, F@_2, TrUserData);
      18 ->
	  d_field_msgTest1_ss(Rest, 0, 0, F@_1, F@_2, TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_msgTest1(Rest, 0, 0, F@_1, F@_2,
				     TrUserData);
	    1 ->
		skip_64_msgTest1(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    2 ->
		skip_length_delimited_msgTest1(Rest, 0, 0, F@_1, F@_2,
					       TrUserData);
	    3 ->
		skip_group_msgTest1(Rest, Key bsr 3, 0, F@_1, F@_2,
				    TrUserData);
	    5 ->
		skip_32_msgTest1(Rest, 0, 0, F@_1, F@_2, TrUserData)
	  end
    end;
dg_read_field_def_msgTest1(<<>>, 0, 0, F@_1, F@_2, _) ->
    #msgTest1{ii = F@_1, ss = F@_2}.

d_field_msgTest1_ii(<<1:1, X:7, Rest/binary>>, N, Acc,
		    F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_msgTest1_ii(Rest, N + 7, X bsl N + Acc, F@_1,
			F@_2, TrUserData);
d_field_msgTest1_ii(<<0:1, X:7, Rest/binary>>, N, Acc,
		    _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    id(Res, TrUserData)
			  end,
			  Rest},
    dfp_read_field_def_msgTest1(RestF, 0, 0, NewFValue,
				F@_2, TrUserData).

d_field_msgTest1_ss(<<1:1, X:7, Rest/binary>>, N, Acc,
		    F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_msgTest1_ss(Rest, N + 7, X bsl N + Acc, F@_1,
			F@_2, TrUserData);
d_field_msgTest1_ss(<<0:1, X:7, Rest/binary>>, N, Acc,
		    F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {id(binary:copy(Bytes), TrUserData), Rest2}
			 end,
    dfp_read_field_def_msgTest1(RestF, 0, 0, F@_1,
				NewFValue, TrUserData).

skip_varint_msgTest1(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    skip_varint_msgTest1(Rest, Z1, Z2, F@_1, F@_2,
			 TrUserData);
skip_varint_msgTest1(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_msgTest1(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_length_delimited_msgTest1(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    skip_length_delimited_msgTest1(Rest, N + 7,
				   X bsl N + Acc, F@_1, F@_2, TrUserData);
skip_length_delimited_msgTest1(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_msgTest1(Rest2, 0, 0, F@_1, F@_2,
				TrUserData).

skip_group_msgTest1(Bin, FNum, Z2, F@_1, F@_2,
		    TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_msgTest1(Rest, 0, Z2, F@_1, F@_2,
				TrUserData).

skip_32_msgTest1(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_msgTest1(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_64_msgTest1(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_msgTest1(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

decode_msg_msgTest2(Bin, TrUserData) ->
    dfp_read_field_def_msgTest2(Bin, 0, 0,
				id(0, TrUserData), id(<<>>, TrUserData),
				TrUserData).

dfp_read_field_def_msgTest2(<<8, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_msgTest2_ii(Rest, Z1, Z2, F@_1, F@_2,
			TrUserData);
dfp_read_field_def_msgTest2(<<18, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_msgTest2_ss(Rest, Z1, Z2, F@_1, F@_2,
			TrUserData);
dfp_read_field_def_msgTest2(<<>>, 0, 0, F@_1, F@_2,
			    _) ->
    #msgTest2{ii = F@_1, ss = F@_2};
dfp_read_field_def_msgTest2(Other, Z1, Z2, F@_1, F@_2,
			    TrUserData) ->
    dg_read_field_def_msgTest2(Other, Z1, Z2, F@_1, F@_2,
			       TrUserData).

dg_read_field_def_msgTest2(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_msgTest2(Rest, N + 7, X bsl N + Acc,
			       F@_1, F@_2, TrUserData);
dg_read_field_def_msgTest2(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_msgTest2_ii(Rest, 0, 0, F@_1, F@_2, TrUserData);
      18 ->
	  d_field_msgTest2_ss(Rest, 0, 0, F@_1, F@_2, TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_msgTest2(Rest, 0, 0, F@_1, F@_2,
				     TrUserData);
	    1 ->
		skip_64_msgTest2(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    2 ->
		skip_length_delimited_msgTest2(Rest, 0, 0, F@_1, F@_2,
					       TrUserData);
	    3 ->
		skip_group_msgTest2(Rest, Key bsr 3, 0, F@_1, F@_2,
				    TrUserData);
	    5 ->
		skip_32_msgTest2(Rest, 0, 0, F@_1, F@_2, TrUserData)
	  end
    end;
dg_read_field_def_msgTest2(<<>>, 0, 0, F@_1, F@_2, _) ->
    #msgTest2{ii = F@_1, ss = F@_2}.

d_field_msgTest2_ii(<<1:1, X:7, Rest/binary>>, N, Acc,
		    F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_msgTest2_ii(Rest, N + 7, X bsl N + Acc, F@_1,
			F@_2, TrUserData);
d_field_msgTest2_ii(<<0:1, X:7, Rest/binary>>, N, Acc,
		    _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    id(Res, TrUserData)
			  end,
			  Rest},
    dfp_read_field_def_msgTest2(RestF, 0, 0, NewFValue,
				F@_2, TrUserData).

d_field_msgTest2_ss(<<1:1, X:7, Rest/binary>>, N, Acc,
		    F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_msgTest2_ss(Rest, N + 7, X bsl N + Acc, F@_1,
			F@_2, TrUserData);
d_field_msgTest2_ss(<<0:1, X:7, Rest/binary>>, N, Acc,
		    F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {id(binary:copy(Bytes), TrUserData), Rest2}
			 end,
    dfp_read_field_def_msgTest2(RestF, 0, 0, F@_1,
				NewFValue, TrUserData).

skip_varint_msgTest2(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    skip_varint_msgTest2(Rest, Z1, Z2, F@_1, F@_2,
			 TrUserData);
skip_varint_msgTest2(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_msgTest2(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_length_delimited_msgTest2(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    skip_length_delimited_msgTest2(Rest, N + 7,
				   X bsl N + Acc, F@_1, F@_2, TrUserData);
skip_length_delimited_msgTest2(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_msgTest2(Rest2, 0, 0, F@_1, F@_2,
				TrUserData).

skip_group_msgTest2(Bin, FNum, Z2, F@_1, F@_2,
		    TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_msgTest2(Rest, 0, Z2, F@_1, F@_2,
				TrUserData).

skip_32_msgTest2(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_msgTest2(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_64_msgTest2(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_msgTest2(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New)
    when element(1, Prev) =:= element(1, New) ->
    merge_msgs(Prev, New, element(1, Prev), []).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) ->
    merge_msgs(Prev, New, MsgName, []);
merge_msgs(Prev, New, Opts)
    when element(1, Prev) =:= element(1, New),
	 is_list(Opts) ->
    merge_msgs(Prev, New, element(1, Prev), Opts).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      protoID -> merge_msg_protoID(Prev, New, TrUserData);
      cmdTest1 -> merge_msg_cmdTest1(Prev, New, TrUserData);
      cmdTest2 -> merge_msg_cmdTest2(Prev, New, TrUserData);
      msgTest1 -> merge_msg_msgTest1(Prev, New, TrUserData);
      msgTest2 -> merge_msg_msgTest2(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_protoID/3}).
merge_msg_protoID(#protoID{proto_id = PFproto_id,
			   data = PFdata},
		  #protoID{proto_id = NFproto_id, data = NFdata}, _) ->
    #protoID{proto_id =
		 if NFproto_id =:= undefined -> PFproto_id;
		    true -> NFproto_id
		 end,
	     data =
		 if NFdata =:= undefined -> PFdata;
		    true -> NFdata
		 end}.

-compile({nowarn_unused_function,merge_msg_cmdTest1/3}).
merge_msg_cmdTest1(#cmdTest1{ii = PFii, ss = PFss},
		   #cmdTest1{ii = NFii, ss = NFss}, _) ->
    #cmdTest1{ii =
		  if NFii =:= undefined -> PFii;
		     true -> NFii
		  end,
	      ss =
		  if NFss =:= undefined -> PFss;
		     true -> NFss
		  end}.

-compile({nowarn_unused_function,merge_msg_cmdTest2/3}).
merge_msg_cmdTest2(#cmdTest2{ii = PFii, ss = PFss},
		   #cmdTest2{ii = NFii, ss = NFss}, _) ->
    #cmdTest2{ii =
		  if NFii =:= undefined -> PFii;
		     true -> NFii
		  end,
	      ss =
		  if NFss =:= undefined -> PFss;
		     true -> NFss
		  end}.

-compile({nowarn_unused_function,merge_msg_msgTest1/3}).
merge_msg_msgTest1(#msgTest1{ii = PFii, ss = PFss},
		   #msgTest1{ii = NFii, ss = NFss}, _) ->
    #msgTest1{ii =
		  if NFii =:= undefined -> PFii;
		     true -> NFii
		  end,
	      ss =
		  if NFss =:= undefined -> PFss;
		     true -> NFss
		  end}.

-compile({nowarn_unused_function,merge_msg_msgTest2/3}).
merge_msg_msgTest2(#msgTest2{ii = PFii, ss = PFss},
		   #msgTest2{ii = NFii, ss = NFss}, _) ->
    #msgTest2{ii =
		  if NFii =:= undefined -> PFii;
		     true -> NFii
		  end,
	      ss =
		  if NFss =:= undefined -> PFss;
		     true -> NFss
		  end}.


verify_msg(Msg) when tuple_size(Msg) >= 1 ->
    verify_msg(Msg, element(1, Msg), []);
verify_msg(X) ->
    mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName) when is_atom(MsgName) ->
    verify_msg(Msg, MsgName, []);
verify_msg(Msg, Opts) when tuple_size(Msg) >= 1 ->
    verify_msg(Msg, element(1, Msg), Opts);
verify_msg(X, _Opts) ->
    mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      protoID -> v_msg_protoID(Msg, [MsgName], TrUserData);
      cmdTest1 -> v_msg_cmdTest1(Msg, [MsgName], TrUserData);
      cmdTest2 -> v_msg_cmdTest2(Msg, [MsgName], TrUserData);
      msgTest1 -> v_msg_msgTest1(Msg, [MsgName], TrUserData);
      msgTest2 -> v_msg_msgTest2(Msg, [MsgName], TrUserData);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_protoID/3}).
-dialyzer({nowarn_function,v_msg_protoID/3}).
v_msg_protoID(#protoID{proto_id = F1, data = F2}, Path,
	      TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_int32(F1, [proto_id | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_bytes(F2, [data | Path], TrUserData)
    end,
    ok;
v_msg_protoID(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, protoID}, X, Path).

-compile({nowarn_unused_function,v_msg_cmdTest1/3}).
-dialyzer({nowarn_function,v_msg_cmdTest1/3}).
v_msg_cmdTest1(#cmdTest1{ii = F1, ss = F2}, Path,
	       TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_int32(F1, [ii | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_string(F2, [ss | Path], TrUserData)
    end,
    ok;
v_msg_cmdTest1(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, cmdTest1}, X, Path).

-compile({nowarn_unused_function,v_msg_cmdTest2/3}).
-dialyzer({nowarn_function,v_msg_cmdTest2/3}).
v_msg_cmdTest2(#cmdTest2{ii = F1, ss = F2}, Path,
	       TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_int32(F1, [ii | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_string(F2, [ss | Path], TrUserData)
    end,
    ok;
v_msg_cmdTest2(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, cmdTest2}, X, Path).

-compile({nowarn_unused_function,v_msg_msgTest1/3}).
-dialyzer({nowarn_function,v_msg_msgTest1/3}).
v_msg_msgTest1(#msgTest1{ii = F1, ss = F2}, Path,
	       TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_int32(F1, [ii | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_string(F2, [ss | Path], TrUserData)
    end,
    ok;
v_msg_msgTest1(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, msgTest1}, X, Path).

-compile({nowarn_unused_function,v_msg_msgTest2/3}).
-dialyzer({nowarn_function,v_msg_msgTest2/3}).
v_msg_msgTest2(#msgTest2{ii = F1, ss = F2}, Path,
	       TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_int32(F1, [ii | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_string(F2, [ss | Path], TrUserData)
    end,
    ok;
v_msg_msgTest2(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, msgTest2}, X, Path).

-compile({nowarn_unused_function,v_type_int32/3}).
-dialyzer({nowarn_function,v_type_int32/3}).
v_type_int32(N, _Path, _TrUserData)
    when -2147483648 =< N, N =< 2147483647 ->
    ok;
v_type_int32(N, Path, _TrUserData) when is_integer(N) ->
    mk_type_error({value_out_of_range, int32, signed, 32},
		  N, Path);
v_type_int32(X, Path, _TrUserData) ->
    mk_type_error({bad_integer, int32, signed, 32}, X,
		  Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData)
    when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} ->
	  mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg ->
	  mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) ->
    mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,v_type_bytes/3}).
-dialyzer({nowarn_function,v_type_bytes/3}).
v_type_bytes(B, _Path, _TrUserData) when is_binary(B) ->
    ok;
v_type_bytes(B, _Path, _TrUserData) when is_list(B) ->
    ok;
v_type_bytes(X, Path, _TrUserData) ->
    mk_type_error(bad_binary_value, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error,
		  {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) ->
    list_to_atom(lists:append(lists:join(".",
					 lists:map(fun atom_to_list/1,
						   lists:reverse(PathR))))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{enum, 'cmdTest1.info'},
      [{option, allow_alias, true}, {unknown, 0},
       {proto_id, 1001}, {aaa, 1}, {bbb, 1}]},
     {{enum, 'cmdTest2.info'},
      [{option, allow_alias, true}, {unknown, 0},
       {proto_id, 1002}, {bag, 1}, {email, 0}]},
     {{msg, protoID},
      [#field{name = proto_id, fnum = 1, rnum = 2,
	      type = int32, occurrence = optional, opts = []},
       #field{name = data, fnum = 2, rnum = 3, type = bytes,
	      occurrence = optional, opts = []}]},
     {{msg, cmdTest1},
      [#field{name = ii, fnum = 2, rnum = 2, type = int32,
	      occurrence = optional, opts = []},
       #field{name = ss, fnum = 3, rnum = 3, type = string,
	      occurrence = optional, opts = []}]},
     {{msg, cmdTest2},
      [#field{name = ii, fnum = 1, rnum = 2, type = int32,
	      occurrence = optional, opts = []},
       #field{name = ss, fnum = 2, rnum = 3, type = string,
	      occurrence = optional, opts = []}]},
     {{msg, msgTest1},
      [#field{name = ii, fnum = 1, rnum = 2, type = int32,
	      occurrence = optional, opts = []},
       #field{name = ss, fnum = 2, rnum = 3, type = string,
	      occurrence = optional, opts = []}]},
     {{msg, msgTest2},
      [#field{name = ii, fnum = 1, rnum = 2, type = int32,
	      occurrence = optional, opts = []},
       #field{name = ss, fnum = 2, rnum = 3, type = string,
	      occurrence = optional, opts = []}]}].


get_msg_names() ->
    [protoID, cmdTest1, cmdTest2, msgTest1, msgTest2].


get_group_names() -> [].


get_msg_or_group_names() ->
    [protoID, cmdTest1, cmdTest2, msgTest1, msgTest2].


get_enum_names() -> ['cmdTest1.info', 'cmdTest2.info'].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


fetch_enum_def(EnumName) ->
    case find_enum_def(EnumName) of
      Es when is_list(Es) -> Es;
      error -> erlang:error({no_such_enum, EnumName})
    end.


find_msg_def(protoID) ->
    [#field{name = proto_id, fnum = 1, rnum = 2,
	    type = int32, occurrence = optional, opts = []},
     #field{name = data, fnum = 2, rnum = 3, type = bytes,
	    occurrence = optional, opts = []}];
find_msg_def(cmdTest1) ->
    [#field{name = ii, fnum = 2, rnum = 2, type = int32,
	    occurrence = optional, opts = []},
     #field{name = ss, fnum = 3, rnum = 3, type = string,
	    occurrence = optional, opts = []}];
find_msg_def(cmdTest2) ->
    [#field{name = ii, fnum = 1, rnum = 2, type = int32,
	    occurrence = optional, opts = []},
     #field{name = ss, fnum = 2, rnum = 3, type = string,
	    occurrence = optional, opts = []}];
find_msg_def(msgTest1) ->
    [#field{name = ii, fnum = 1, rnum = 2, type = int32,
	    occurrence = optional, opts = []},
     #field{name = ss, fnum = 2, rnum = 3, type = string,
	    occurrence = optional, opts = []}];
find_msg_def(msgTest2) ->
    [#field{name = ii, fnum = 1, rnum = 2, type = int32,
	    occurrence = optional, opts = []},
     #field{name = ss, fnum = 2, rnum = 3, type = string,
	    occurrence = optional, opts = []}];
find_msg_def(_) -> error.


find_enum_def('cmdTest1.info') ->
    [{option, allow_alias, true}, {unknown, 0},
     {proto_id, 1001}, {aaa, 1}, {bbb, 1}];
find_enum_def('cmdTest2.info') ->
    [{option, allow_alias, true}, {unknown, 0},
     {proto_id, 1002}, {bag, 1}, {email, 0}];
find_enum_def(_) -> error.


enum_symbol_by_value('cmdTest1.info', Value) ->
    'enum_symbol_by_value_cmdTest1.info'(Value);
enum_symbol_by_value('cmdTest2.info', Value) ->
    'enum_symbol_by_value_cmdTest2.info'(Value).


enum_value_by_symbol('cmdTest1.info', Sym) ->
    'enum_value_by_symbol_cmdTest1.info'(Sym);
enum_value_by_symbol('cmdTest2.info', Sym) ->
    'enum_value_by_symbol_cmdTest2.info'(Sym).


'enum_symbol_by_value_cmdTest1.info'(0) -> unknown;
'enum_symbol_by_value_cmdTest1.info'(1001) -> proto_id;
'enum_symbol_by_value_cmdTest1.info'(1) -> aaa.


'enum_value_by_symbol_cmdTest1.info'(unknown) -> 0;
'enum_value_by_symbol_cmdTest1.info'(proto_id) -> 1001;
'enum_value_by_symbol_cmdTest1.info'(aaa) -> 1;
'enum_value_by_symbol_cmdTest1.info'(bbb) -> 1.

'enum_symbol_by_value_cmdTest2.info'(0) -> unknown;
'enum_symbol_by_value_cmdTest2.info'(1002) -> proto_id;
'enum_symbol_by_value_cmdTest2.info'(1) -> bag.


'enum_value_by_symbol_cmdTest2.info'(unknown) -> 0;
'enum_value_by_symbol_cmdTest2.info'(proto_id) -> 1002;
'enum_value_by_symbol_cmdTest2.info'(bag) -> 1;
'enum_value_by_symbol_cmdTest2.info'(email) -> 0.


get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) ->
    erlang:error({no_such_rpc, ServiceName, RpcName}).


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
-spec fqbin_to_service_name(_) -> no_return().
fqbin_to_service_name(X) ->
    error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
-spec service_name_to_fqbin(_) -> no_return().
service_name_to_fqbin(X) ->
    error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
-spec fqbins_to_service_and_rpc_name(_, _) -> no_return().
fqbins_to_service_and_rpc_name(S, R) ->
    error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
-spec service_and_rpc_name_to_fqbins(_, _) -> no_return().
service_and_rpc_name_to_fqbins(S, R) ->
    error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"cmd.protoID">>) -> protoID;
fqbin_to_msg_name(<<"cmd.cmdTest1">>) -> cmdTest1;
fqbin_to_msg_name(<<"cmd.cmdTest2">>) -> cmdTest2;
fqbin_to_msg_name(<<"cmd.msgTest1">>) -> msgTest1;
fqbin_to_msg_name(<<"cmd.msgTest2">>) -> msgTest2;
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin(protoID) -> <<"cmd.protoID">>;
msg_name_to_fqbin(cmdTest1) -> <<"cmd.cmdTest1">>;
msg_name_to_fqbin(cmdTest2) -> <<"cmd.cmdTest2">>;
msg_name_to_fqbin(msgTest1) -> <<"cmd.msgTest1">>;
msg_name_to_fqbin(msgTest2) -> <<"cmd.msgTest2">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


fqbin_to_enum_name(<<"cmd.cmdTest1.info">>) -> 'cmdTest1.info';
fqbin_to_enum_name(<<"cmd.cmdTest2.info">>) -> 'cmdTest2.info';
fqbin_to_enum_name(E) ->
    error({gpb_error, {badenum, E}}).


enum_name_to_fqbin('cmdTest1.info') -> <<"cmd.cmdTest1.info">>;
enum_name_to_fqbin('cmdTest2.info') -> <<"cmd.cmdTest2.info">>;
enum_name_to_fqbin(E) ->
    error({gpb_error, {badenum, E}}).


get_package_name() -> cmd.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> false.


source_basename() -> "all.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() ->
    ["all.proto", "cmd.proto", "msg.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["all", "cmd", "msg"].


get_msg_containment("all") -> [protoID];
get_msg_containment("cmd") -> [cmdTest1, cmdTest2];
get_msg_containment("msg") -> [msgTest1, msgTest2];
get_msg_containment(P) ->
    error({gpb_error, {badproto, P}}).


get_pkg_containment("all") -> undefined;
get_pkg_containment("cmd") -> undefined;
get_pkg_containment("msg") -> undefined;
get_pkg_containment(P) ->
    error({gpb_error, {badproto, P}}).


get_service_containment("all") -> [];
get_service_containment("cmd") -> [];
get_service_containment("msg") -> [];
get_service_containment(P) ->
    error({gpb_error, {badproto, P}}).


get_rpc_containment("all") -> [];
get_rpc_containment("cmd") -> [];
get_rpc_containment("msg") -> [];
get_rpc_containment(P) ->
    error({gpb_error, {badproto, P}}).


get_enum_containment("all") -> [];
get_enum_containment("cmd") ->
    ['cmdTest1.info', 'cmdTest2.info'];
get_enum_containment("msg") -> [];
get_enum_containment(P) ->
    error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"cmd.msgTest1">>) -> "msg";
get_proto_by_msg_name_as_fqbin(<<"cmd.cmdTest1">>) -> "cmd";
get_proto_by_msg_name_as_fqbin(<<"cmd.msgTest2">>) -> "msg";
get_proto_by_msg_name_as_fqbin(<<"cmd.cmdTest2">>) -> "cmd";
get_proto_by_msg_name_as_fqbin(<<"cmd.protoID">>) -> "all";
get_proto_by_msg_name_as_fqbin(E) ->
    error({gpb_error, {badmsg, E}}).


-spec get_proto_by_service_name_as_fqbin(_) -> no_return().
get_proto_by_service_name_as_fqbin(E) ->
    error({gpb_error, {badservice, E}}).


get_proto_by_enum_name_as_fqbin(<<"cmd.cmdTest2.info">>) -> "cmd";
get_proto_by_enum_name_as_fqbin(<<"cmd.cmdTest1.info">>) -> "cmd";
get_proto_by_enum_name_as_fqbin(E) ->
    error({gpb_error, {badenum, E}}).


-spec get_protos_by_pkg_name_as_fqbin(_) -> no_return().
get_protos_by_pkg_name_as_fqbin(E) ->
    error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.10.0".

gpb_version_as_list() ->
    [4,10,0].
